### ISSUE TITLE
Wrong python path in Image Builder and SDK

### ISSUE THREAD

**Issue by jempatel** [OnionIoT/openwrt-buildsystem-wrapper#12]
# What package does this bug affect?

Customized Image Builder and SDK

# Wrong path of Python binary

Image Builder and SDK generated from the CI/CD, generates python command path from the python virtual environment `/root/.pyenv/shims/python3.8`, instead of using system path, causing failure in generating Image using image builder.

# **To Reproduce**

1. Download the image builder from the 

http://downloads.onioniot.com.s3.amazonaws.com/releases/22.03.3/targets/ramips/mt76x8/openwrt-imagebuilder-v22.03.3-ramips-mt76x8.Linux-x86_64.tar.xz

3. Extract the Image builder.

4. Check python path inside extracted image builder

`# ls -l ./staging_dir/host/bin/python`

It's a soft link and points to `/root/.pyenv/shims/python3.8`

# **Expected behavior**

Python binary path should be pointed to the system's default python command, Path generated from the CI/CD `/root/.pyenv/shims/python3.8` might not be available to users using SDK or they might not be using python from that specific path.

# **Additional context**

This might be caused because of config in `buildspec.yml`.

```yml
phases:
  install:
    runtime-versions:
      python: 3.8
```

We might need to use `apt-get install python3.8` and install python to make it available in the build system.

**Comment by greenbreakfast** [comment]
### Some additional context:

Our AWS CodeBuild is setup to use the AWS (Ubuntu) Standard 5.0 docker image for the environment: https://github.com/OnionIoT/openwrt-buildsystem-wrapper/blob/openwrt-22.03/.terraform/pipeline/modules/codebuild/main.tf#L32

The AWS (Ubuntu) Standard 5.0 docker image seems to 1) be based on Ubuntu 20.04: https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/5.0/Dockerfile#L11

and 2) setup pyenv and then modify the path to use the problematic `/root/.pyenv/shims` path for python: https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/5.0/Dockerfile#L160

---

We should be using Ubuntu 22.04 for all of our CI. So this means either using AWS (Ubuntu) Standard 6.0 or 7.0.
Or, to get around this python path issue, maybe we use the ubuntu 22.04 docker image directly?

@amine605 let me know what you think

**Comment by greenbreakfast** [comment]
Confirming PR #13 fixes the issue for both the SDK and the image builder

sdk:
<img width="758" alt="image" src="https://user-images.githubusercontent.com/6757320/234990496-12a3d55d-980e-4823-932c-e4b2f9dcc2d3.png">

image builder:
<img width="705" alt="image" src="https://user-images.githubusercontent.com/6757320/234990406-15f1d73f-62c6-4f4f-9309-be4b16cf409c.png">

---

@amine605 can you please make the same updates to the pipeline that builds the [SDK wrapper](https://github.com/OnionIoT/openwrt-sdk-wrapper) and [Image builder wrapper](https://github.com/OnionIoT/openwrt-imagebuilder-wrapper) repos? 
(The terraform files are in the OpenWRT-packages repo: https://github.com/OnionIoT/OpenWRT-Packages/tree/openwrt-22.03/.terraform)

**Comment by greenbreakfast** [comment]
Fixed in SDK + image builder CD pipeline as well: 
* https://github.com/OnionIoT/openwrt-sdk-wrapper/pull/7
* https://github.com/OnionIoT/openwrt-imagebuilder-wrapper/pull/7
* https://github.com/OnionIoT/OpenWRT-Packages/pull/54

Closing this issue. Thanks @amine605
