### ISSUE TITLE
Migration to OpenWRT 23.05.3 - Major Release Part 2

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/openwrt-buildsystem-wrapper#24]
# Context

Specify which branch of this repo or firmware version you're referring to

new openwrt-23.05 branch

# Motivation

Why are we doing this? What use cases does it support? What problems does it solve? What is the expected outcome?

The purpose of this scope is to update our firmware to OpenWRT 23.05.3

This scope is working with the new OpenWRT release so it has a major impact on all 3 value tracks

Development
Deployment
Production

- The goal is to release firmware based on the new OpenWRT release built with Onion’s customized SDK and Image Builder 

> In Part 1 Ticket #85, we resolved any migration specific issues. Now that we have a running firmware on the new release, let’s add in Onion’s customizations

Steps

1. Create a new branch in the openwrt-buildsystem-wrapper repo
    1. The branch should be based on the previous release and should be named to match OpenWRT release name, for example `openwrt-22.03` for OpenWRT 22.03
2. Update the openwrt-buildsystem-wrapper repo configuration to use the build system commit used for the target release
3. Successfully compile the build system with our customizations
    - Debug compilation issues as needed by **updating patches** and our config files
    - To move forward:
        - build system needs to compile without errors
        - output SDK should be tested
        - output Image Builder should be tested
4. Build custom packages and new firmware based on the customized SDK and Image Builder
    1. Update the openwrt-imagebuilder-wrapper repo configuration to use **Onion’s customized** Image Builder for the target release
    2. Update the openwrt-sdk-wrapper repo configuration to use  **Onion’s customized** SDK for the target release
    3. Build packages and fimrware

###  2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.

1. Implement the mentioned steps.
2. Identify and address any issues that arise.
3. Implement the tests in the checklist below and provide test results accordingly. 

# Additional Resources

Provide hyperlinks for helpful and related information.

- OnionIoT/openwrt-buildsystem-wrapper

# **The Workflow:**
- [ ] Subtask 1: Execute the mentioned steps to perform Part 2 of the migration.
- [ ] Subtask 2: Execute the test process in Ticket #48 
- [ ] Subtask 3: Review test results for approval to release the new firmware.

# Deliverables

* `openwrt-23.05` branch in OnionIoT/openwrt-buildsystem-wrapper repo that is configured to compile the build system based on the openwrt-23.05.3 release
* Successful compilation of the build system
* Updates to SDK and Image builder Wrapper configuration files (in OnionIoT/openwrt-packages repo) to use **Onion’s customized** SDK and Image Builder, respectively
* Successful compilation of packages using the SDK wrapper
* Successful compilation of firmware using the image builder wrapper

**Comment by greenbreakfast** [comment]
@amsiotdeveloper 

> 4. Build custom packages and new firmware based on the customized SDK and Image Builder
>    
>    1. Update the openwrt-imagebuilder-wrapper repo configuration to use **Onion’s customized** Image Builder for the target release
>    2. Update the openwrt-sdk-wrapper repo configuration to use  **Onion’s customized** SDK for the target release
>    3. Build packages and fimrware

building off [my comment](https://github.com/OnionIoT/OpenWRT-Packages/issues/85#issuecomment-1964629427) in #85:

The updates to the openwrt-imagebuilder-wrapper and openwrt-sdk-wrapper configuration should take place in the `imagebuilder-profile` and `sdk-profile` files respectively in the OnionIoT/openwrt-packages repo

**Comment by greenbreakfast** [comment]
Released update to 23.05.3 here: https://github.com/OnionIoT/openwrt-buildsystem-wrapper/releases/tag/23.05.3-20240607

SDK and Image Builder zips here: http://downloads.onioniot.com/releases/23.05.3/targets/ramips/mt76x8/
Baseline OpenWRT packages here: http://downloads.onioniot.com/releases/23.05.3/packages/mipsel_24kc/

Made a release in OpenWRT-Packages repo to build Onion packages and firmware based on the customized SDK and Image Builder here: https://github.com/OnionIoT/OpenWRT-Packages/releases/tag/23.05.3-20240607

Firmware available here: http://repo.onioniot.com/omega2/images/openwrt-23.05/
Onion packages available here: http://repo.onioniot.com/omega2/packages/openwrt-23.05.3/onion/

Closing this issue!
