### ISSUE TITLE
Small build process updates 

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/openwrt-buildsystem-wrapper#6]
Two modification requests for the build process - mostly to make CI/CD easier:

1. No longer do verbose build system compilation by default
2. No longer do complete clean-up after build - it's nice to be able to poke around the system after compilation is complete
3. If there is a `keys` directory, copy the contents to where it needs to be in the build system, and make sure the packages get signed with this key

EDIT: Added Item 3 on Tuesday, Mar 21, 4:30pm EST

**Comment by jempatel** [comment]
@greenbreakfast  Is there any action to take up from my end for this?

**Comment by greenbreakfast** [comment]
@jempatel yes, can you please make the required changes to the build script?

**Comment by jempatel** [comment]
@greenbreakfast Script already has support for that but its argument based, If you want that I can make it by default to not cleanup post build.

**Comment by greenbreakfast** [comment]
@jempatel yes, please make [all 3 items from above](https://github.com/OnionIoT/openwrt-buildsystem-wrapper/issues/6#issue-1632609165) the default behaviour

**Comment by greenbreakfast** [comment]
Updated in PR #9 - will close this issue when CD setup (#7) is complete and we do a test build

**Comment by greenbreakfast** [comment]
Additional update in PR #11 - closing this issue now, will reopen if necessary
