### ISSUE TITLE
Setup CD for this repo 

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/openwrt-buildsystem-wrapper#7]
## Goal
Setup a reliable and maintainable Continuous Deployment setup on AWS for building OpenWRT packages and binaries using this OpenWRT Build System wrapper

## Output

* AWS CD setup, including buildspec file in this repo
* Package files and binary files created as output of build system should be hosted publicly

## Dependencies

Not a blocking dependency, but #6 should be completed

**Comment by greenbreakfast** [comment]
@amine605 do you have an estimate on when CD setup will be done?

**Comment by amine-troudi** [comment]
@greenbreakfast The build is taking too much time, Code build is timing out. I proposed some solutions in DM, Please let me know what you think.

**Comment by greenbreakfast** [comment]
Marking this as complete and closing the issue.

### Some info
When a release is created in this GitHub repo, the CD will build packages and firmware and make them available at http://downloads.onioniot.com

Packages and firmware from each release will be stored - the URL is based on the GitHub Release Tag: `http://downloads.onioniot.com/builds/22.03.3/<RELEASE-TAG>`

The very latest build will be available at `http://downloads.onioniot.com/releases/22.03.3/`
